version: '3'
services:
  database:
    image: quay.io/maksymbilenko/oracle-xe-11g
    environment:
      - ORACLE_DISABLE_ASYNCH_IO=true
    volumes:
      - D:\tmp\oracle\init:/docker-entrypoint-initdb.d/
      - D:\tmp\oracle\unicredit\oradata:/u01/app/oracle # persistent oracle database data.
#      - D:\tmp\oracle\unicredit\scripts\db-script:/opt/db/config
    ports:
      - 1521:1521
  artemis:
    image: dkr-registry.tasgroup.it/redhat/amq-broker:7.6
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: admin
      AMQ_TRANSPORTS: CORE
      AMQ_QUEUES: DLQ.MSS.MESSAGE01.FROM.BOA, MSS.MESSAGE01.FROM.BOA, MSS.MESSAGE01.REPLY.BOA, MSS.MESSAGE02.FROM.BOA, MSS.MESSAGE01.TO.BOA, DLQ.MSS.MESSAGE02.FROM.BOA, MSS.MESSAGE02.TO.BOA, MSS.MESSAGE02.REPLY.BOA, MSS.MESSAGE03.FROM.BOA, MSS.MESSAGE03.REPLY.BOA, DLQ.MSS.MESSAGE03.FROM.BOA, MSS.MESSAGE03.TO.BOA, DLQ.MSS.MESSAGE04.FROM.BOA, MSS.MESSAGE04.FROM.BOA, MSS.MESSAGE04.REPLY.BOA, MSS.MESSAGE05.FROM.BOA, MSS.MESSAGE04.TO.BOA, DLQ.MSS.MESSAGE05.FROM.BOA, MSS.MESSAGE05.TO.BOA, MSS.MESSAGE05.REPLY.BOA, MSS.MESSAGE06.FROM.BOA, MSS.MESSAGE06.REPLY.BOA, DLQ.MSS.MESSAGE06.FROM.BOA, MSS.MESSAGE06.TO.BOA, DLQ.MSS.MESSAGE07.FROM.BOA, MSS.MESSAGE07.FROM.BOA, MSS.MESSAGE07.REPLY.BOA, MSS.MESSAGE08.FROM.BOA, MSS.MESSAGE07.TO.BOA, DLQ.MSS.MESSAGE08.FROM.BOA, MSS.MESSAGE08.TO.BOA, MSS.MESSAGE08.REPLY.BOA, MSS.MESSAGE09.FROM.BOA, MSS.MESSAGE09.REPLY.BOA, DLQ.MSS.MESSAGE09.FROM.BOA, MSS.MESSAGE09.TO.BOA, DLQ.MSS.MESSAGE10.FROM.BOA, MSS.MESSAGE10.FROM.BOA, MSS.MESSAGE10.REPLY.BOA, AA00.INPUT, MSS.MESSAGE10.TO.BOA, AA00.REPLY, AA00.OUTPUT, DLQ.AA00.REPLY, DLQ.AA00.OUTPUT
      AMQ_ADDRESSES: FinConfigurationTopic
    ports:
      - 61616:61616
      - 8161:8161
  jboss:
    image: gitlab.int.master.lan:5005/netgat/fin/fin-unicredit-amq
#    build:
#      context: ./target
#      dockerfile: Dockerfile
    env_file:
      - file.env
    environment:
      DEBUG: "true"
      GC_MAX_METASPACE_SIZE: 1024
    ports:
      - 9990:9990
      - 8080:8080
      - 8787:8787
    depends_on:
      - database
      - artemis

