CREATE TABLESPACE "TS_DATA"
  DATAFILE 'TS_DATA..dbf'
  SIZE 32M AUTOEXTEND ON NEXT 32M MAXSIZE 2G
  LOGGING
  EXTENT MANAGEMENT LOCAL
  ONLINE
  SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "TS_INDEX"
  DATAFILE 'TS_INDEX..dbf'
  SIZE 32M AUTOEXTEND ON NEXT 32M MAXSIZE 1G
  LOGGING
  EXTENT MANAGEMENT LOCAL
  ONLINE
  SEGMENT SPACE MANAGEMENT AUTO;

--
-- Create OWNER
--
CREATE USER "DB_OWNER" PROFILE "DEFAULT" IDENTIFIED BY "DB_OWNER"
  DEFAULT TABLESPACE "TS_DATA"
    TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
    GRANT "CONNECT" TO "DB_OWNER";
    GRANT "RESOURCE" TO "DB_OWNER";
    GRANT CREATE VIEW TO "DB_OWNER";

--
-- Create USER
--
CREATE USER "DB_USER" PROFILE "DEFAULT" IDENTIFIED BY "DB_USER"
  DEFAULT TABLESPACE "TS_DATA"
    TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
    GRANT "CONNECT" TO "DB_USER";
    GRANT CREATE SYNONYM TO "DB_USER";
    GRANT EXECUTE ON SYS.DBMS_LOCK TO "DB_USER";
--
-- Assign default tablespaces
--
alter user DB_OWNER default tablespace TS_DATA;
alter user DB_USER  default tablespace TS_DATA;
