--
-- Schema "root value"
-- Example: QLT_FOO gives QLT_FOO_OWNER, QLT_FOO_USER, TD_QLT_FOO...
-- Uncomment and edit the line below or wait to be prompted by SQL*Plus
-- 
def SCHEMA_ROOT = 'JENKINS'

--
-- Generate variables
--
def SCHEMA_OWNER = &&SCHEMA_ROOT._OWNER
def SCHEMA_USER  = &&SCHEMA_ROOT._USER
def TS_DATA      = TD_&&SCHEMA_ROOT
def TS_INDEX     = TI_&&SCHEMA_ROOT

-- Remove old users, schemas and objects. Uncomment as needed
--
-- drop user "&&SCHEMA_OWNER" cascade;
-- drop user "&&SCHEMA_USER" cascade;

--
-- Create tablespaces
--

CREATE TABLESPACE "&&TS_DATA"
  DATAFILE '&&TS_DATA..dbf'
  SIZE 32M AUTOEXTEND ON NEXT 32M MAXSIZE 2G
  LOGGING
  EXTENT MANAGEMENT LOCAL
  ONLINE
  SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "&&TS_INDEX"
  DATAFILE '&&TS_INDEX..dbf'
  SIZE 32M AUTOEXTEND ON NEXT 32M MAXSIZE 1G
  LOGGING
  EXTENT MANAGEMENT LOCAL
  ONLINE
  SEGMENT SPACE MANAGEMENT AUTO;
  
--
-- Create OWNER
--
CREATE USER "&&DB_OWNER" PROFILE "DEFAULT" IDENTIFIED BY "&&DB_OWNER"
  DEFAULT TABLESPACE "&&TS_DATA"
    TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
    GRANT "CONNECT" TO "&&DB_OWNER";
    GRANT "RESOURCE" TO "&&DB_OWNER";
    GRANT CREATE VIEW TO "&&DB_OWNER";
    GRANT CREATE ANY SYNONYM TO "&&DB_OWNER";
    GRANT EXECUTE ON sys.dbms_crypto TO "&&DB_OWNER";
    GRANT CREATE PROCEDURE TO "&&DB_OWNER";
    GRANT EXECUTE ON sys.UTL_RAW TO "&&DB_OWNER";

--
-- Create USER
--
CREATE USER "&&SCHEMA_USER" PROFILE "DEFAULT" IDENTIFIED BY "&&SCHEMA_USER"
  DEFAULT TABLESPACE "&&TS_DATA"
    TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
    GRANT "CONNECT" TO "&&SCHEMA_USER";
    GRANT "RESOURCE" TO "&&SCHEMA_USER";
    GRANT CREATE VIEW TO "&&SCHEMA_USER";
    GRANT CREATE ANY SYNONYM TO "&&SCHEMA_USER";
    GRANT EXECUTE ON sys.dbms_crypto TO "&&SCHEMA_USER";
    GRANT CREATE PROCEDURE TO "&&SCHEMA_USER";
    GRANT EXECUTE ON sys.UTL_RAW TO "&&SCHEMA_USER";
--
-- Assign default tablespaces
--
alter user &&DB_OWNER default tablespace &&TS_DATA;
alter user &&SCHEMA_USER  default tablespace &&TS_DATA;

COMMIT;

ALTER SYSTEM SET processes=200 scope=spfile;

QUIT
