version: '3'
services:
  mq:
    image: gitlab.int.master.lan:5005/netgat/fin/fin-unicredit-ibmmq:dev
    ports:
      - "1414:1414"
    environment:
      - "TZ=Europe/Rome"
      - "MAXHEAP=2048"
  database:
    image: quay.io/maksymbilenko/oracle-xe-11g
    environment:
      - ORACLE_DISABLE_ASYNCH_IO=true
    volumes:
      - D:\tmp\oracle\init:/docker-entrypoint-initdb.d/
      - D:\tmp\oracle\unicredit\oradata:/u01/app/oracle # persistent oracle database data.
#      - D:\tmp\oracle\unicredit\scripts\db-script:/opt/db/config
    ports:
      - 1521:1521
  artemis:
    image: dkr-registry.tasgroup.it/redhat/amq-broker:7.6
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: admin
      AMQ_TRANSPORTS: CORE
      AMQ_QUEUES: MSS.MESSAGEAMQ01.TO.BOA, MSS.MESSAGEAMQ01.FROM.BOA, MSS.MESSAGEAMQ01.REPLY.BOA, MSS.MESSAGEAMQ02.TO.BOA, MSS.MESSAGEAMQ02.FROM.BOA, MSS.MESSAGEAMQ02.REPLY.BOA, MSS.MESSAGEAMQ03.TO.BOA, MSS.MESSAGEAMQ03.FROM.BOA, MSS.MESSAGEAMQ03.REPLY.BOA, MSS.MESSAGEAMQ04.TO.BOA, MSS.MESSAGEAMQ04.FROM.BOA, MSS.MESSAGEAMQ04.REPLY.BOA, MSS.MESSAGEAMQ05.TO.BOA, MSS.MESSAGEAMQ05.FROM.BOA, MSS.MESSAGEAMQ05.REPLY.BOA, MSS.MESSAGEAMQ06.TO.BOA, MSS.MESSAGEAMQ06.FROM.BOA, MSS.MESSAGEAMQ06.REPLY.BOA, MSS.MESSAGEAMQ07.TO.BOA, MSS.MESSAGEAMQ07.FROM.BOA, MSS.MESSAGEAMQ07.REPLY.BOA, MSS.MESSAGEAMQ08.TO.BOA, MSS.MESSAGEAMQ08.FROM.BOA, MSS.MESSAGEAMQ08.REPLY.BOA, MSS.MESSAGEAMQ09.TO.BOA, MSS.MESSAGEAMQ09.FROM.BOA, MSS.MESSAGEAMQ09.REPLY.BOA, MSS.MESSAGEAMQ10.TO.BOA, MSS.MESSAGEAMQ10.FROM.BOA, MSS.MESSAGEAMQ10.REPLY.BOA,
      AMQ_ADDRESSES: FinConfigurationTopic
    ports:
      - 61616:61616
      - 8161:8161
  jboss:
    build:
      context: ./target
      dockerfile: Dockerfile
    env_file:
      - file.env
    environment:
      DEBUG: "true"
      GC_MAX_METASPACE_SIZE: 1024
    ports:
      - 9990:9990
      - 8080:8080
      - 8787:8787
    depends_on:
      - database
      - mq
      - artemis
