version: '3'
services:
  oracle-psd2:
    build:
      context: .
      dockerfile: oracle.Dockerfile
    ports:
      - "1521:1521"
  liquibase:
    build:
      context: .
      dockerfile: liquibase.Dockerfile
    entrypoint: ["/bin/wait-for-it.sh","oracle-psd2:8080","--timeout=0","--strict", "--", "/liquibase/liquibase" ]
    command: --url=jdbc:oracle:thin:@oracle-psd2:1521:XE --classpath=/liquibase/lib/ojdbc.jar --changeLogFile=eu/tasgroup/psd2/db/changelog/db.changelog-DDL-master.xml --username=OWNER --password=OWNER --contexts=owner update -Ddb.owner=OWNER -Ddb.user=OWNER -DtablesTablespaceName=TS_DATA -DindexesTablespaceName=TS_INDEX
    depends_on:
      - oracle-psd2
