CREATE TABLESPACE "TS_DATA"
  DATAFILE 'TS_DATA..dbf'
  SIZE 32M AUTOEXTEND ON NEXT 32M MAXSIZE 2G
  LOGGING
  EXTENT MANAGEMENT LOCAL
  ONLINE
  SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "TS_INDEX"
  DATAFILE 'TS_INDEX..dbf'
  SIZE 32M AUTOEXTEND ON NEXT 32M MAXSIZE 1G
  LOGGING
  EXTENT MANAGEMENT LOCAL
  ONLINE
  SEGMENT SPACE MANAGEMENT AUTO;

 CREATE USER "OWNER" PROFILE "DEFAULT" IDENTIFIED BY "OWNER"
  DEFAULT TABLESPACE "TS_DATA"
    TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
    GRANT "CONNECT" TO "OWNER";
    GRANT "RESOURCE" TO "OWNER";
    GRANT CREATE VIEW TO "OWNER";
    GRANT CREATE ANY SYNONYM TO "OWNER";

alter user OWNER default tablespace TS_DATA;
