version: '3'
services:
  mq:
    image: dkr-registry.tasgroup.it:5000/supportwas/mqseries
    volumes:
      - ./ibmmq:/etc/mqm/
    ports:
      - "1414:1414"
    environment:
      - "TZ=Europe/Rome"
      - "MAXHEAP=2048"
#  database:
#    image: oracle/database:12.1.0.2-ee
#    volumes:
#      - /home/oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
#    ports:
#      - 1521:1521
#      - 8080:8080
#      - 5500:5500
